" Vim color file
"   This file was generated by Palette
"   http://rubygems.org/gems/palette
"
" Author: Fernando Espinosa
" Notes:  Dark scheme

hi clear
if version > 580
    if exists("syntax_on")
        syntax reset
    endif
endif

let colors_name="ferdev"

if has("gui_running")
    set background=dark
endif

hi Normal guifg=#0033CC ctermfg=26   guibg=#333333 ctermbg=236  gui=NONE cterm=NONE
hi Folded guifg=#808080 ctermfg=244  guibg=#ECECEC ctermbg=255  gui=BOLD cterm=BOLD

hi link vimFold    Folded
hi link FoldColumn Folded
" Vim color file
"   This file was generated by Palette
"   http://rubygems.org/gems/palette
"
" Author: Fernando Espinosa
" Notes:  Dark scheme

hi clear
if version > 580
    if exists("syntax_on")
        syntax reset
    endif
endif

let colors_name="ferdev"

if has("gui_running")
    set background=dark
endif

hi Normal guifg=#3366CC ctermfg=62   guibg=#333333 ctermbg=236  gui=NONE cterm=NONE
hi Folded guifg=#808080 ctermfg=244  guibg=#ECECEC ctermbg=255  gui=BOLD cterm=BOLD

hi link vimFold    Folded
hi link FoldColumn Folded
" Vim color file
"   This file was generated by Palette
"   http://rubygems.org/gems/palette
"
" Author: Fernando Espinosa
" Notes:  Dark scheme

hi clear
if version > 580
    if exists("syntax_on")
        syntax reset
    endif
endif

let colors_name="ferdev"

if has("gui_running")
    set background=dark
endif

hi Normal guifg=#3366CC ctermfg=62   guibg=#4C4C4C ctermbg=239  gui=NONE cterm=NONE
hi Folded guifg=#808080 ctermfg=244  guibg=#ECECEC ctermbg=255  gui=BOLD cterm=BOLD

hi link vimFold    Folded
hi link FoldColumn Folded
" Vim color file
"   This file was generated by Palette
"   http://rubygems.org/gems/palette
"
" Author: Fernando Espinosa
" Notes:  Dark scheme

hi clear
if version > 580
    if exists("syntax_on")
        syntax reset
    endif
endif

let colors_name="ferdev"

if has("gui_running")
    set background=dark
endif

hi Normal guifg=#6699FF ctermfg=69   guibg=#4C4C4C ctermbg=239  gui=NONE cterm=NONE
hi Folded guifg=#808080 ctermfg=244  guibg=#ECECEC ctermbg=255  gui=BOLD cterm=BOLD

hi link vimFold    Folded
hi link FoldColumn Folded
" Vim color file
"   This file was generated by Palette
"   http://rubygems.org/gems/palette
"
" Author: Fernando Espinosa
" Notes:  Dark scheme

hi clear
if version > 580
    if exists("syntax_on")
        syntax reset
    endif
endif

let colors_name="ferdev"

if has("gui_running")
    set background=dark
endif

hi Normal guifg=#6699FF ctermfg=69   guibg=#202020 ctermbg=234  gui=NONE cterm=NONE
hi Folded guifg=#808080 ctermfg=244  guibg=#ECECEC ctermbg=255  gui=BOLD cterm=BOLD

hi link vimFold    Folded
hi link FoldColumn Folded
" Vim color file
"   This file was generated by Palette
"   http://rubygems.org/gems/palette
"
" Author: Fernando Espinosa
" Notes:  Dark scheme

hi clear
if version > 580
    if exists("syntax_on")
        syntax reset
    endif
endif

let colors_name="ferdev"

if has("gui_running")
    set background=dark
endif

hi Normal guifg=#CE6E4D ctermfg=167  guibg=#202020 ctermbg=234  gui=NONE cterm=NONE
hi Folded guifg=#808080 ctermfg=244  guibg=#ECECEC ctermbg=255  gui=BOLD cterm=BOLD

hi link vimFold    Folded
hi link FoldColumn Folded
" Vim color file
"   This file was generated by Palette
"   http://rubygems.org/gems/palette
"
" Author: Fernando Espinosa
" Notes:  Dark scheme

hi clear
if version > 580
    if exists("syntax_on")
        syntax reset
    endif
endif

let colors_name="ferdev"

if has("gui_running")
    set background=dark
endif

hi Normal guifg=#AA92ED ctermfg=141  guibg=#202020 ctermbg=234  gui=NONE cterm=NONE
hi Folded guifg=#808080 ctermfg=244  guibg=#ECECEC ctermbg=255  gui=BOLD cterm=BOLD

hi link vimFold    Folded
hi link FoldColumn Folded
